(function(){
  'use strict';
  var root=document.getElementById('aromika-promos-page'); if(!root) return;
  var feed=root.getAttribute('data-feed')||'https://raw.githubusercontent.com/dickort/aromika-site/main/data/promos.json';
  var demo=root.getAttribute('data-demo')==='1';
  var standalonePreview=root.getAttribute('data-preview')==='1';
  var grid=root.querySelector('[data-promos-grid]'), empty=root.querySelector('[data-promos-empty]'), demoNote=root.querySelector('[data-demo-note]');
  var current='all', sortMode='discount'; var dataset=[];
  function savedLang(){try{return localStorage.getItem('aromika-language')||'ru';}catch(e){return 'ru';}}
  var ru=savedLang()!=='kk';
  var copy={ru:{updated:'Обновлено',unknown:'данные ещё не получены',sourceA:'Aromika.shop',sourceK:'Kaspi.kz',ok:'акции загружены',empty:'активных скидок сейчас нет',error:'временно недоступен — показываем последнюю успешную выгрузку',buyA:'Купить на Aromika.shop',buyK:'Купить на Kaspi.kz',save:'Экономия',noneTitle:'Сейчас здесь нет активных акций',noneText:'Как только в выбранном источнике появятся товары со скидкой, они автоматически появятся на этой странице.',demo:'Демо-режим: карточки ниже показывают дизайн страницы. Они не считаются актуальными акциями.'},kk:{updated:'Жаңартылды',unknown:'деректер әлі алынбады',sourceA:'Aromika.shop',sourceK:'Kaspi.kz',ok:'акциялар жүктелді',empty:'қазір белсенді жеңілдіктер жоқ',error:'уақытша қолжетімсіз — соңғы сәтті жүктеу көрсетіледі',buyA:'Aromika.shop-та сатып алу',buyK:'Kaspi.kz-та сатып алу',save:'Үнем',noneTitle:'Қазір белсенді акциялар жоқ',noneText:'Таңдалған дереккөзде жеңілдіктер пайда болған кезде, олар бұл бетте автоматты түрде көрсетіледі.',demo:'Демо-режим: төмендегі карточкалар бет дизайнын көрсетеді. Олар ағымдағы акция болып саналмайды.'}};

  var header=document.getElementById('aromika-hero'), footer=document.getElementById('aromika-footer');
  var headerDict={ru:{products:'Продукция',brands:'Бренды',promos:'Акции',about:'О компании',partners:'Партнёрам',careers:'Работа в компании',contacts:'Контакты',buyOnline:'Купить онлайн',shop:'Интернет-магазин'},kk:{products:'Өнімдер',brands:'Брендтер',promos:'Акциялар',about:'Компания туралы',partners:'Серіктестерге',careers:'Компаниядағы жұмыс',contacts:'Байланыс',buyOnline:'Онлайн сатып алу',shop:'Интернет-дүкен'}};
  var footerDict={ru:{brandText:'Казахстанский производитель бытовой химии и косметической продукции.',shopBtn:'Интернет-магазин',company:'Компания',about:'О компании',production:'Производство',contacts:'Контакты',careers:'Работа в компании',brands:'Бренды',allBrands:'Все бренды',partners:'Партнёрам',distributors:'Дистрибьюторам',retail:'Торговым сетям',corporate:'Корпоративным клиентам',buyers:'Покупателям',promos:'Акции',catalog:'Каталог',online:'Интернет-магазин',where:'Где купить',office:'Головной офис',city:'Костанай, Казахстан',phone:'Телефон',feedback:'Обратная связь',top:'Наверх'},kk:{brandText:'Қазақстандық тұрмыстық химия және косметикалық өнім өндірушісі.',shopBtn:'Интернет-дүкен',company:'Компания',about:'Компания туралы',production:'Өндіріс',contacts:'Байланыс',careers:'Компаниядағы жұмыс',brands:'Брендтер',allBrands:'Барлық брендтер',partners:'Серіктестерге',distributors:'Дистрибьюторларға',retail:'Сауда желілеріне',corporate:'Корпоративтік клиенттерге',buyers:'Сатып алушыларға',promos:'Акциялар',catalog:'Каталог',online:'Интернет-дүкен',where:'Қайдан сатып алуға болады',office:'Бас кеңсе',city:'Қостанай, Қазақстан',phone:'Телефон',feedback:'Кері байланыс',top:'Жоғары'}};
  function c(){return copy[ru?'ru':'kk'];}
  function money(n){return new Intl.NumberFormat(ru?'ru-RU':'kk-KZ',{maximumFractionDigits:0}).format(Number(n)||0)+' ₸';}
  function pct(p){return Math.max(0,Math.round(Number(p)||0));}
  function escapeText(x){return String(x==null?'':x);}
  function brandOf(name){var s=String(name||''); var brands=['Perfect','Wash Expert','Maxi Power','Prachka','Antibak','Aromika','Beauty ESSENCE','Topface']; for(var i=0;i<brands.length;i++) if(s.toLowerCase().indexOf(brands[i].toLowerCase())>-1) return brands[i]; return 'Aromika';}
  function status(source,meta){var el=root.querySelector('[data-status="'+source+'"]');if(!el)return;var st=(meta&&meta.status)||'empty', count=(meta&&meta.count)||0;el.setAttribute('data-state',st);var label=source==='aromika'?c().sourceA:c().sourceK;var msg=st==='ok'?(c().ok+' · '+count):st==='warning'?((ru?'обновление не удалось — показываем предыдущие данные':'жаңарту сәтсіз — алдыңғы деректер көрсетіледі')+' · '+count):st==='pending'?(ru?'ожидает первой автоматической выгрузки':'алғашқы автоматты жүктеуді күтуде'):st==='error'?c().error:c().empty;el.querySelector('strong').textContent=label;el.querySelector('span:last-child').textContent=msg;}
  function setUpdated(v){var el=root.querySelector('[data-updated]');if(!el)return;if(!v){el.textContent=c().updated+': '+c().unknown;return;}try{var d=new Date(v);el.textContent=c().updated+': '+new Intl.DateTimeFormat(ru?'ru-RU':'kk-KZ',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Qostanay'}).format(d);}catch(e){el.textContent=c().updated+': '+v;}}
  function render(){var items=dataset.filter(function(p){return current==='all'||p.source===current;});items.sort(function(a,b){if(sortMode==='price')return (a.price||0)-(b.price||0);return (b.discount||0)-(a.discount||0);});grid.querySelectorAll('.ap-card,.ap-skeleton').forEach(function(n){n.remove();});if(!items.length){empty.classList.add('is-visible');empty.querySelector('b').textContent=c().noneTitle;empty.querySelector('p').textContent=c().noneText;return;}empty.classList.remove('is-visible');items.forEach(function(p){var a=document.createElement('a');a.className='ap-card';a.href=p.url||'#';a.target='_blank';a.rel='noopener';a.setAttribute('data-source',p.source||'aromika');var media=document.createElement('div');media.className='ap-media';var img=document.createElement('img');img.loading='lazy';img.alt=escapeText(p.name);img.src=p.image||'';img.onerror=function(){this.style.opacity='.08';};media.appendChild(img);var badge=document.createElement('span');badge.className='ap-discount';badge.textContent='−'+pct(p.discount)+'%';media.appendChild(badge);var src=document.createElement('span');src.className='ap-source';src.textContent=p.source==='kaspi'?'KASPI':'AROMIKA.SHOP';media.appendChild(src);a.appendChild(media);var body=document.createElement('div');body.className='ap-body';var br=document.createElement('div');br.className='ap-brand';br.textContent=p.brand||brandOf(p.name);body.appendChild(br);var nm=document.createElement('div');nm.className='ap-name';nm.textContent=p.name||'';body.appendChild(nm);var price=document.createElement('div');price.className='ap-price';var strong=document.createElement('strong');strong.textContent=money(p.price);price.appendChild(strong);if(p.old_price){var del=document.createElement('del');del.textContent=money(p.old_price);price.appendChild(del);}body.appendChild(price);if(p.old_price&&p.price&&p.old_price>p.price){var sv=document.createElement('div');sv.className='ap-saving';sv.textContent=c().save+': '+money(p.old_price-p.price);body.appendChild(sv);}var cta=document.createElement('div');cta.className='ap-cta';var ct=document.createElement('span');ct.textContent=p.source==='kaspi'?c().buyK:c().buyA;var ar=document.createElement('span');ar.textContent='↗';cta.append(ct,ar);body.appendChild(cta);a.appendChild(body);grid.appendChild(a);});}
  function applyLanguage(force){var lang=(force==='kk'||force==='ru')?force:savedLang();ru=lang!=='kk';document.documentElement.lang=lang==='kk'?'kk':'ru';root.querySelectorAll('[data-ap-ru]').forEach(function(el){el.textContent=ru?el.getAttribute('data-ap-ru'):el.getAttribute('data-ap-kk');});if(header)header.querySelectorAll('[data-i18n]').forEach(function(el){var k=el.getAttribute('data-i18n');if(headerDict[lang][k]!=null)el.textContent=headerDict[lang][k];});if(header)header.querySelectorAll('[data-ap-nav]').forEach(function(el){var k=el.getAttribute('data-ap-nav');if(headerDict[lang][k]!=null)el.textContent=headerDict[lang][k];});if(footer)footer.querySelectorAll('[data-arf-i18n]').forEach(function(el){var k=el.getAttribute('data-arf-i18n');if(footerDict[lang][k]!=null)el.textContent=footerDict[lang][k];});document.querySelectorAll('[data-lang]').forEach(function(b){var on=b.getAttribute('data-lang')===lang;b.classList.toggle('is-active',on);b.classList.toggle('arf-active',on);});try{localStorage.setItem('aromika-language',lang)}catch(e){}if(window.__apData){status('aromika',window.__apData.sources&&window.__apData.sources.aromika);status('kaspi',window.__apData.sources&&window.__apData.sources.kaspi);setUpdated(window.__apData.updated_at);}if(demoNote&&demoNote.classList.contains('is-visible'))demoNote.textContent=c().demo;render();}
  root.querySelectorAll('.ap-tab').forEach(function(btn){btn.addEventListener('click',function(){root.querySelectorAll('.ap-tab').forEach(function(b){b.classList.remove('is-active');});btn.classList.add('is-active');current=btn.getAttribute('data-source');render();});});
  var sort=root.querySelector('.ap-sort');if(sort)sort.addEventListener('click',function(){sortMode=sortMode==='discount'?'price':'discount';sort.textContent=sortMode==='discount'?(ru?'Сначала максимальная скидка':'Алдымен ең үлкен жеңілдік'):(ru?'Сначала дешевле':'Алдымен арзанырақ');render();});
  document.addEventListener('click',function(e){var b=e.target.closest('[data-lang]');if(b){var chosen=b.getAttribute('data-lang');try{localStorage.setItem('aromika-language',chosen)}catch(x){}applyLanguage(chosen);}});
  window.addEventListener('storage',function(e){if(e.key==='aromika-language')applyLanguage();});document.addEventListener('aromika:languagechange',applyLanguage);
  if(header){var burger=header.querySelector('.ar-burger'),menu=header.querySelector('.ar-menu'),overlay=header.querySelector('.ar-overlay');function menuOpen(on){if(!burger||!menu||!overlay)return;burger.classList.toggle('open',on);menu.classList.toggle('open',on);overlay.classList.toggle('open',on);document.body.style.overflow=on?'hidden':'';}if(burger)burger.addEventListener('click',function(){menuOpen(!menu.classList.contains('open'));});if(overlay)overlay.addEventListener('click',function(){menuOpen(false);});if(menu)menu.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){menuOpen(false);});});}
  var THEME_KEY='aromika-theme';function currentTheme(){return document.documentElement.getAttribute('data-aromika-theme')||'light';}function renderTheme(){var t=currentTheme()==='dark'?'dark':'light';document.documentElement.setAttribute('data-aromika-theme',t);document.documentElement.style.colorScheme=t;document.querySelectorAll('.ar-theme-toggle').forEach(function(b){b.setAttribute('aria-pressed',t==='dark'?'true':'false');b.setAttribute('aria-label',t==='dark'?'Включить светлую тему':'Включить тёмную тему');});}document.querySelectorAll('.ar-theme-toggle').forEach(function(b){b.addEventListener('click',function(){var t=currentTheme()==='dark'?'light':'dark';try{localStorage.setItem(THEME_KEY,t);}catch(e){}document.documentElement.setAttribute('data-aromika-theme',t);renderTheme();});});renderTheme();
  function demoData(){return {updated_at:new Date().toISOString(),demo:true,sources:{aromika:{status:'ok',count:3},kaspi:{status:'ok',count:2}},products:[{source:'aromika',name:'Гель для стирки «Perfect Aromika» Black & Dark 3300 мл',brand:'Perfect',old_price:3416,price:2904,discount:15,image:'https://aromika.shop/images/detailed/138/Perfect_WG_Black_Dark_3300_.webp',url:'https://aromika.shop/vse-tovary/gel-dlya-stirki-perfect-aromika-black-and-dark-3300-ml/'},{source:'aromika',name:'Бессульфатный шампунь «Beauty ESSENCE» Keratin 800 мл',brand:'Beauty ESSENCE',old_price:2018,price:1715,discount:15,image:'https://aromika.shop/images/detailed/138/Sh_BeautyESSENCE_Keratin.png',url:'https://aromika.shop/vse-tovary/aromika-beauty-essence-bessulfatnyy-shampun-keratinoterapiya-800ml/'},{source:'aromika',name:'Шампунь «Beauty ESSENCE» Восстановление 800 мл',brand:'Beauty ESSENCE',old_price:1656,price:1408,discount:15,image:'https://aromika.shop/images/detailed/138/Sh_BeautyESSENCE_Keratin.png',url:'https://aromika.shop/'},{source:'kaspi',name:'Гель для стирки Aromika Wash Expert Color 4,3 л',brand:'Wash Expert',old_price:4200,price:3360,discount:20,image:'https://cdn.jsdelivr.net/gh/dickort/aromika-site@main/images/wash-expert.png',url:'https://kaspi.kz/shop/p/aromika-wash-expert-color-4-3-l-102029665/'},{source:'kaspi',name:'Гель для стирки «Perfect Aromika» White 3.3 л',brand:'Perfect',old_price:3800,price:3230,discount:15,image:'https://cdn.jsdelivr.net/gh/dickort/aromika-site@main/images/perfect.png',url:'https://kaspi.kz/shop/p/aromika-gel-dlja-stirki-perfect-aromika-white-3-3-l-117499666/'}]};}
  fetch(feed+(feed.indexOf('?')>-1?'&':'?')+'t='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('feed '+r.status);return r.json();}).then(function(data){if(demo&&(!data.products||!data.products.length))data=demoData();window.__apData=data;dataset=(data.products||[]).filter(function(p){return Number(p.discount)>0&&Number(p.price)>0;});if(data.demo||demo&&dataset.length){demoNote.classList.add('is-visible');demoNote.textContent=c().demo;}status('aromika',data.sources&&data.sources.aromika);status('kaspi',data.sources&&data.sources.kaspi);setUpdated(data.updated_at);render();}).catch(function(){var data=demo?demoData():{products:[],sources:{aromika:{status:'error'},kaspi:{status:'error'}}};window.__apData=data;dataset=data.products||[];if(demo){demoNote.classList.add('is-visible');demoNote.textContent=c().demo;}status('aromika',data.sources.aromika);status('kaspi',data.sources.kaspi);setUpdated(data.updated_at);render();});
  applyLanguage();
})();